package com.lazydoglab.zisee.ar.annotation

import com.lazydoglab.zisee.ar.session.MarkerKind
import com.lazydoglab.zisee.ar.spatial.SpatialRejection
import com.lazydoglab.zisee.media.MediaTrack
import org.json.JSONObject
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.util.UUID

/** Versioned payloads for a future dedicated, reliable ordered DataChannel (zisee-ar-v1).
 * sessionId is generated by the field device at AR entry. Never accept an unannounced epoch.
 * Coordinates, pose and depth remain session-local; no world coordinates are sent to the server.
 */
sealed interface ArMessage {
    val sessionId: UUID
    data class Ready(override val sessionId: UUID, val depthSupported: Boolean) : ArMessage
    data class Create(override val sessionId: UUID, val id: UUID, val kind: MarkerKind, val request: SpatialMarkerRequest) : ArMessage
    data class Remove(override val sessionId: UUID, val id: UUID) : ArMessage
    data class Clear(override val sessionId: UUID) : ArMessage
    /** null rejection acknowledges successful creation. It does not represent a persistent anchor. */
    data class Result(override val sessionId: UUID, val id: UUID, val rejection: SpatialRejection?) : ArMessage
}

sealed interface ArDecodeResult {
    data class Message(val value: ArMessage) : ArDecodeResult
    data object Invalid : ArDecodeResult
    data object UnsupportedVersion : ArDecodeResult
    data object TooLarge : ArDecodeResult
}

object ArProtocol {
    const val CHANNEL_LABEL = "zisee-ar-v1"
    const val MAX_BYTES = 4096
    fun encode(message: ArMessage): ByteArray {
        val json = JSONObject().put("v", 1).put("sessionId", message.sessionId.toString())
        when (message) {
            is ArMessage.Ready -> json.put("type", "ready").put("depth", message.depthSupported)
            is ArMessage.Create -> {
                require(message.request.frame.track == MediaTrack.BACK_CAMERA && message.request.frame.timestampNs > 0)
                json.put("type", "create").put("id", message.id.toString()).put("kind", message.kind.name)
                    .put("track", message.request.frame.track.wireId)
                    // JSON numbers cannot round-trip 64-bit nanoseconds through every peer implementation.
                    .put("timestampNs", message.request.frame.timestampNs.toString())
                    .put("x", message.request.point.x).put("y", message.request.point.y)
            }
            is ArMessage.Remove -> json.put("type", "remove").put("id", message.id.toString())
            is ArMessage.Clear -> json.put("type", "clear")
            is ArMessage.Result -> json.put("type", "result").put("id", message.id.toString())
                .put("rejection", message.rejection?.name ?: JSONObject.NULL)
        }
        return json.toString().toByteArray(Charsets.UTF_8).also { require(it.size <= MAX_BYTES) }
    }

    fun decode(bytes: ByteArray): ArDecodeResult {
        if (bytes.size > MAX_BYTES) return ArDecodeResult.TooLarge
        return try {
            val text = Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes)).toString()
            // This protocol is flat. Reject nesting before JSONTokener can recurse on peer input.
            if (!isFlatObject(text)) return ArDecodeResult.Invalid
            val tokenizer = org.json.JSONTokener(text)
            val json = tokenizer.nextValue() as? JSONObject ?: return ArDecodeResult.Invalid
            if (tokenizer.nextClean() != '\u0000') return ArDecodeResult.Invalid
            val version = json.get("v")
            if (version !is Int) return ArDecodeResult.Invalid
            if (version != 1) return ArDecodeResult.UnsupportedVersion
            val epoch = uuid(json, "sessionId")
            fun keys(vararg fields: String) {
                require(json.keys().asSequence().toSet() == setOf("v", "type", "sessionId", *fields))
            }
            val message = when (json.get("type")) {
                "ready" -> { keys("depth"); ArMessage.Ready(epoch, json.get("depth") as Boolean) }
                "create" -> {
                    keys("id", "kind", "track", "timestampNs", "x", "y")
                    require(json.get("track") == MediaTrack.BACK_CAMERA.wireId)
                    val timestamp = json.get("timestampNs") as String
                    val ns = timestamp.toLong()
                    require(ns > 0 && ns.toString() == timestamp)
                    val x = (json.get("x") as Number).toDouble()
                    val y = (json.get("y") as Number).toDouble()
                    require(x in 0.0..1.0 && y in 0.0..1.0)
                    ArMessage.Create(epoch, uuid(json, "id"), MarkerKind.valueOf(json.get("kind") as String),
                        SpatialMarkerRequest(VideoFrameReference(MediaTrack.BACK_CAMERA, ns), VideoPoint(x.toFloat(), y.toFloat())))
                }
                "remove" -> { keys("id"); ArMessage.Remove(epoch, uuid(json, "id")) }
                "clear" -> { keys(); ArMessage.Clear(epoch) }
                "result" -> {
                    keys("id", "rejection")
                    val rejection = json.get("rejection")
                    ArMessage.Result(epoch, uuid(json, "id"), if (rejection == JSONObject.NULL) null else SpatialRejection.valueOf(rejection as String))
                }
                else -> return ArDecodeResult.Invalid
            }
            ArDecodeResult.Message(message)
        } catch (_: Exception) { ArDecodeResult.Invalid }
    }

    private fun uuid(json: JSONObject, key: String): UUID {
        val text = json.get(key) as String
        return UUID.fromString(text).also { require(it.toString() == text) }
    }

    private fun isFlatObject(text: String): Boolean {
        var quoted = false
        var escaped = false
        var depth = 0
        for (character in text) {
            if (quoted) {
                if (escaped) escaped = false
                else if (character == '\\') escaped = true
                else if (character == '"') quoted = false
            } else when (character) {
                '"' -> quoted = true
                '{' -> { depth++; if (depth > 1) return false }
                '}' -> { depth--; if (depth < 0) return false }
                '[', ']', '\'' -> return false
            }
        }
        return !quoted && depth == 0
    }
}
